[test]
coverage = true
coverageReporter = ["text", "lcov"]
coverageDir = "./coverage/bun"
coverageSkipTestFiles = true
coveragePathIgnorePatterns = [
  "**/node_modules/**",
  "**/tests/config/**",
  "**/auth-client.ts",
  "**/packages/db/prisma/generated/**",
  "**/e2e/**",
  "**/presence/e2e/**"
]
testFilePattern = "**/*.test.{ts,tsx}"
exclude = [
  "**/e2e/**",
  "**/presence/e2e/**",
  "**/node_modules/**",
  "**/*.spec.ts",
  "**/apps/presence/e2e/**"
]
