services:
  lumendb:
    image: postgres:18.3
    container_name: lumendb
    restart: unless-stopped
    environment:
      POSTGRES_DB: lumendb
      POSTGRES_USER: lumen
      POSTGRES_PASSWORD: lumen
    ports:
      - "5154:5432"
    volumes:
      - lumendb-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lumen -d lumendb"]
      interval: 5s
      timeout: 5s
      retries: 20

  lumencache:
    image: redis:8.6.2
    container_name: lumencache
    restart: unless-stopped
    ports:
      - "5354:6379"
    volumes:
      - lumencache-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 20

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: lumen-otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./monitoring/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"
    depends_on:
      - tempo
      - loki
      - prometheus

  tempo:
    image: grafana/tempo:latest
    container_name: lumen-tempo
    command: ["-config.file=/etc/tempo.yaml"]
    user: "0:0"
    volumes:
      - ./monitoring/tempo-config.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4417:4317"

  loki:
    image: grafana/loki:latest
    container_name: lumen-loki
    command: ["-config.file=/etc/loki/local-config.yaml"]
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki

  prometheus:
    image: prom/prometheus:latest
    container_name: lumen-prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.enable-remote-write-receiver"
    volumes:
      - ./monitoring/prometheus-config.yaml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9099:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: lumen-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    volumes:
      - ./monitoring/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./monitoring/grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./dashboards:/etc/grafana/provisioning/dashboards
      - grafana-data:/var/lib/grafana
    ports:
      - "3333:3000"
    depends_on:
      - tempo
      - loki
      - prometheus

volumes:
  lumendb-data:
  lumencache-data:
  tempo-data:
  loki-data:
  prometheus-data:
  grafana-data:
